---
- name: Playbook for deploying SQL
  hosts: localhost
  tasks: 
    - name: Create a resource group
      azure_rm_resourcegroup: 
        name: ansible_demo1003
        location: australiaeast
    - name: Create a MySQL Server
      azure_rm_mysqlserver:
        resource_group: ansible_demo1003
        name: demoserver120
        sku:
          name: B_Gen5_1
          tier: Basic
        location: australiaeast
        storage_mb: 5120
        enforce_ssl: True
        version: 5.6
        admin_username: lijinnong
        admin_password: Test123456
    




      




